/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;
import java.applet.AudioClip;
/**
 *
 * @author aruns
 */
public class calculadora extends javax.swing.JFrame {

    public float primernumero;
    public float segundonumero;
    public String operador;
    
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_operacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_multiplicacion = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_result = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(33, 43, 65));

        txt_operacion.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        txt_operacion.setForeground(new java.awt.Color(0, 229, 175));
        txt_operacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(txt_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(txt_operacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 170));

        jPanel1.setBackground(new java.awt.Color(46, 57, 81));

        btn_1.setBackground(new java.awt.Color(33, 43, 65));
        btn_1.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_1.setForeground(new java.awt.Color(0, 229, 175));
        btn_1.setText("1");
        btn_1.setBorderPainted(false);
        btn_1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(33, 43, 65));
        btn_2.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_2.setForeground(new java.awt.Color(0, 229, 175));
        btn_2.setText("2");
        btn_2.setBorderPainted(false);
        btn_2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(33, 43, 65));
        btn_3.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_3.setForeground(new java.awt.Color(0, 229, 175));
        btn_3.setText("3");
        btn_3.setBorderPainted(false);
        btn_3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_suma.setBackground(new java.awt.Color(33, 43, 65));
        btn_suma.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_suma.setForeground(new java.awt.Color(0, 229, 175));
        btn_suma.setText("+");
        btn_suma.setBorderPainted(false);
        btn_suma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(33, 43, 65));
        btn_4.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_4.setForeground(new java.awt.Color(0, 229, 175));
        btn_4.setText("4");
        btn_4.setBorderPainted(false);
        btn_4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(33, 43, 65));
        btn_5.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_5.setForeground(new java.awt.Color(0, 229, 175));
        btn_5.setText("5");
        btn_5.setBorderPainted(false);
        btn_5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(33, 43, 65));
        btn_6.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_6.setForeground(new java.awt.Color(0, 229, 175));
        btn_6.setText("6");
        btn_6.setBorderPainted(false);
        btn_6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_resta.setBackground(new java.awt.Color(33, 43, 65));
        btn_resta.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_resta.setForeground(new java.awt.Color(0, 229, 175));
        btn_resta.setText("-");
        btn_resta.setBorderPainted(false);
        btn_resta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_7.setBackground(new java.awt.Color(33, 43, 65));
        btn_7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_7.setForeground(new java.awt.Color(0, 229, 175));
        btn_7.setText("7");
        btn_7.setBorderPainted(false);
        btn_7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(33, 43, 65));
        btn_8.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_8.setForeground(new java.awt.Color(0, 229, 175));
        btn_8.setText("8");
        btn_8.setBorderPainted(false);
        btn_8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(33, 43, 65));
        btn_9.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_9.setForeground(new java.awt.Color(0, 229, 175));
        btn_9.setText("9");
        btn_9.setBorderPainted(false);
        btn_9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_multiplicacion.setBackground(new java.awt.Color(33, 43, 65));
        btn_multiplicacion.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_multiplicacion.setForeground(new java.awt.Color(0, 229, 175));
        btn_multiplicacion.setText("*");
        btn_multiplicacion.setBorderPainted(false);
        btn_multiplicacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multiplicacionActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(33, 43, 65));
        btn_0.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_0.setForeground(new java.awt.Color(0, 229, 175));
        btn_0.setText("0");
        btn_0.setBorderPainted(false);
        btn_0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(33, 43, 65));
        btn_punto.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(0, 229, 175));
        btn_punto.setText(".");
        btn_punto.setBorderPainted(false);
        btn_punto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_result.setBackground(new java.awt.Color(0, 229, 175));
        btn_result.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_result.setForeground(new java.awt.Color(255, 255, 255));
        btn_result.setText("=");
        btn_result.setBorderPainted(false);
        btn_result.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_result.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultActionPerformed(evt);
            }
        });

        btn_division.setBackground(new java.awt.Color(33, 43, 65));
        btn_division.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_division.setForeground(new java.awt.Color(0, 229, 175));
        btn_division.setText("/");
        btn_division.setBorderPainted(false);
        btn_division.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        btn_borrar.setBackground(new java.awt.Color(112, 43, 65));
        btn_borrar.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        btn_borrar.setForeground(new java.awt.Color(204, 204, 204));
        btn_borrar.setText("CE");
        btn_borrar.setBorderPainted(false);
        btn_borrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_resta, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                            .addComponent(btn_suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_punto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_result, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_result, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 360, 350));

        jMenuBar1.setBackground(new java.awt.Color(14, 37, 68));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(0, 46, 56));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Opciones");

        jMenuItem2.setText("Nuevo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Historial");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(46, 57, 81));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Ayuda");

        jMenuItem1.setText("Manual");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        acerca acerca = new acerca(this, rootPaneCheckingEnabled);
        acerca.setVisible(true);
         AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();       
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        txt_operacion.setText(txt_operacion.getText()+"1");         
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
        
    }//GEN-LAST:event_btn_1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        txt_operacion.setText("");      
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
     
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        txt_operacion.setText(txt_operacion.getText()+"2");         
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
        
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        txt_operacion.setText(txt_operacion.getText()+"3"); 
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
        
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
       this.primernumero=Float.parseFloat(this.txt_operacion.getText());
       this.operador="+";
       this.txt_operacion.setText("");         
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
        
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        txt_operacion.setText(txt_operacion.getText()+"4");       
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();       
        
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        txt_operacion.setText(txt_operacion.getText()+"5");         
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();        
        
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        txt_operacion.setText(txt_operacion.getText()+"6");        
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();        
        
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
       this.primernumero=Float.parseFloat(this.txt_operacion.getText());
       this.operador="-";
       this.txt_operacion.setText("");        
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();      
       
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
      txt_operacion.setText(txt_operacion.getText()+"7");       
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();     
      
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
       txt_operacion.setText(txt_operacion.getText()+"8");        
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();      
       
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
       txt_operacion.setText(txt_operacion.getText()+"9");        
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();       
       
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_multiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multiplicacionActionPerformed
       this.primernumero=Float.parseFloat(this.txt_operacion.getText());
       this.operador="*";
       this.txt_operacion.setText("");        
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();      
       
    }//GEN-LAST:event_btn_multiplicacionActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
       txt_operacion.setText(txt_operacion.getText()+"0");        
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();      
       
    }//GEN-LAST:event_btn_0ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
  if (!(this.txt_operacion.getText().contains("."))){
        txt_operacion.setText(txt_operacion.getText()+".");
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();        
  
  }
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_resultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultActionPerformed
        this.segundonumero=Float.parseFloat(this.txt_operacion.getText());
         AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();       
        switch(this.operador){
            case "+":this.txt_operacion.setText(Float.toString(this.primernumero+this.segundonumero));break;
            case "-":this.txt_operacion.setText(Float.toString(this.primernumero-this.segundonumero));break;
            case "*":this.txt_operacion.setText(Float.toString(this.primernumero*this.segundonumero));break;
            case "/":this.txt_operacion.setText(Float.toString(this.primernumero/this.segundonumero));break;            
        }
        
        
    }//GEN-LAST:event_btn_resultActionPerformed

    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
       this.primernumero=Float.parseFloat(this.txt_operacion.getText());
       this.operador="/";
       this.txt_operacion.setText("");
    
           AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();    
       
    }//GEN-LAST:event_btn_divisionActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
           bitacoracalculadora  bitacoracalculadora = new bitacoracalculadora (this, rootPaneCheckingEnabled);
        bitacoracalculadora.setVisible(true);  
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        txt_operacion.setText("");      
        AudioClip Sound;
        Sound = java.applet.Applet.newAudioClip(getClass().getResource("/wav/Sonido - Click de mouse.wav"));
        Sound.play();
    }//GEN-LAST:event_btn_borrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }
    
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_multiplicacion;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_result;
    private javax.swing.JButton btn_suma;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt_operacion;
    // End of variables declaration//GEN-END:variables
}
